name: cflat-plus
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.9.13
  - pytorch=2.0.1=py3.9_cuda11.8_cudnn8.7.0_0
  - torchvision=0.15.2=py39_cu118
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0=cuda
  - numpy=1.24
  - scipy=1.10
  - pillow
  - tqdm
